[package]
name = "idionautic-agent"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]  # Required for building WebAssembly

[dependencies]
wasm-bindgen = "0.2"

# Optional logging dependencies for debugging purposes
log = "0.4"  
console_log = "0.2"
