name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout `idionautic-agent` repository
        uses: actions/checkout@v2

      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - name: Download `idionautic-server` release
        run: wget https://github.com/navicore/idionautic-server/releases/download/v0.1.13/idionautic-server_0.1.13_Linux_x86_64.tar.gz

      - name: Extract `idionautic-server`
        run: tar -xzf idionautic-server_0.1.13_Linux_x86_64.tar.gz

      - name: Start `idionautic-server`
        run: ./idionautic-server &

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Wait for server to start
        run: sleep 3

      - name: Run wasm-pack Integration Tests
        run: wasm-pack test --headless --chrome

