name: Build and Test WebAssembly

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install wasm-pack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build with wasm-pack
        run: wasm-pack build --target web
      
      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable

      - name: Download `idionautic-server` release
        run: wget https://github.com/navicore/idionautic-server/releases/download/v0.1.15/idionautic-server_0.1.15_Linux_x86_64.tar.gz

      - name: Extract `idionautic-server`
        run: tar -xzf idionautic-server_0.1.15_Linux_x86_64.tar.gz

      - name: Start `idionautic-server`
        run: ./idionautic-server &

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Wait for server to start
        run: sleep 3

      - name: Run wasm-pack Integration Tests
        run: wasm-pack test --headless --chrome

